FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.8-build-20210225 as buildstep

# Build pip wheels
COPY ./requirements.txt requirements.txt
RUN pip install wheel \
 && mkdir /tmp/wheels \
 && pip wheel -w /tmp/wheels -r requirements.txt

FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.8-build-20210225

ENV UDEV=on

# Install bluetooth. Note: bluez 5.50 fails to write (uart service) -> update to 5.51
RUN install_packages \
    git \
    cifs-utils \
    bluetooth dbus bluez \
    openssh-client

# Copy python wheels built in the previous stage
COPY --from=buildstep /tmp/wheels /tmp/wheels
COPY ./requirements.txt requirements.txt
RUN pip install --no-index --find-links=/tmp/wheels -r requirements.txt \
 && rm -rf /tmp/wheels && rm requirements.txt

# Post-install script (iot-kernel)
COPY ./post_install.sh .
RUN chmod 755 post_install.sh \
    && ./post_install.sh \
    && rm post_install.sh

COPY ./start.sh /root/start.sh
WORKDIR /iot
CMD [ "/bin/bash", "/root/start.sh" ]
